version: "3.7"

volumes:
        db-data:

networks:
  instavote:
    driver: bridge

services:
  vote:
   image: chanzin/vote:master
   ports:
    - 5000:80
   depends_on:
    - redis
   networks:
    - instavote

  redis:
   image: redis:alpine
   networks:
    - instavote

  db:
    image: postgres:9.4
    networks:
     - instavote
    environment:
          POSTGRES_DB: "db"
          POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
     - "db-data:/var/lib/postgresql/data"

  result:
   image: chanzin/result:master
   networks:
    - instavote
   ports:
    - 5001:4000
   depends_on:
    - db

  worker:
   image: chanzin/worker:master
   networks:
    - instavote
   depends_on:
     - redis
     - db