pipeline {
    
    agent any
    
    tools {
        maven 'Maven 3.8.1'
    }
    
    stages {
        stage('Build'){
            when{
                changeset "**/worker/**"
            }
            steps {
                echo 'Compiling worker app..'
                dir('worker'){
                sh 'mvn compile' 
                }
            }
        }
        
        stage('Test') {
            when{
                changeset "**/worker/**"
            }
            steps {
                echo 'Running Unit Tests on worker app.'
                 dir('worker'){
                sh 'mvn clean test' 
                }
            }
        }
        
        stage('Package'){
            when{
                branch 'master'
                changeset "**/worker/**"
            }
            steps{
                echo 'Packaging worker app'
                 dir('worker'){
                sh 'mvn package -DskipTests'
                archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true 
                }
                
            }
        }
    }
    post{
        always{
            echo 'Pipeline for worker is completed.'
        }
    }
}
