pipeline {
    
    agent any
    
    tools {
        maven 'Maven 3.8.1'
    }
    
    stages {
        stage('Build'){
            steps {
                echo 'Compiling worker app..'
                dir('worker'){
                sh 'mvn compile' 
                }
            }
        }
        
        stage('Test') {
            steps {
                echo 'Running Unit Test on worker app.'
                 dir('worker'){
                sh 'mvn clean test' 
                }
            }
        }
        
        stage('Package'){
            steps{
                echo 'Packaging worker app'
                 dir('worker'){
                sh 'mvn package' 
                }
                
            }
        }
    }
    post{
        always{
            echo 'Pipeline for worker is completed.'
        }
    }
}
